### ISSUE TITLE
Problem in discord

### ISSUE THREAD

**Issue by T3ARR** [SarnaxLii/SarnaxLii#1]
Hello Sarnax,
My discord username is T3AR#8564 and I had ordered a $30 Valorant cheat from you but right now I do not see your discord server and I am unable to send you a private message on discord, so could you update me about the situation?

Regards,
T3AR

**Comment by SarnaxLii** [comment]
Server me delete Please DM in Gmail

: > SarnaxLii@gmail.com

**Comment by T3ARR** [comment]
i have sent you an email please check

**Comment by T3ARR** [comment]
still waiting on the email reply
